from typing import Protocol
from services.usersService.src.Modules.Users.Domain.Entities.adminEntity import Admin

class IAdminRepository(Protocol):
    def save(self, user: Admin) -> None: ...
    
    def find_by_email(self, email: str) -> Admin | None: ...
    
    def find_by_id(self, id: int) -> Admin | None: ...
    
    def find_by_username(self, username: str) -> Admin | None: ...
    
    def find_all(self) -> list[Admin]: ...
    
    def update(self, user: Admin) -> None: ...
    
    def delete(self, id: int) -> None: ...
    
