from typing import Optional, Protocol

from services.usersService.src.Modules.Users.Domain.Entities.atendenteEntity import Atendente

class IAtendenteRepository(Protocol):
    def save(self, user: dict) -> None: ...
    
    def find_by_email(self, email: str) -> Optional[Atendente] : ...
    
    def find_by_id(self, id: int) -> Optional[Atendente] : ...
    
    def find_by_username(self, username: str) -> Optional[Atendente]: ...
    
    def find_all(self) -> list[Atendente]: ...
    
    def update(self, user: Atendente) -> None: ...
    
    def delete(self, id: int) -> None: ...
    
