from typing import Protocol

from ....domain.entities.Pacient import Pacient


class IPacientRepository(Protocol):
    def save(self, pacient: Pacient) -> Pacient: ...
    def find_by_email(self, email: str) -> Pacient | None: ...
    def find_by_id(self, id: int) -> Pacient | None: ...
    def find_by_username(self, username: str) -> Pacient | None: ...
    def find_all(self) -> list[Pacient]: ...
    def update(self, id: int, data: dict) -> Pacient | None: ...
    def delete(self, id: int) -> bool: ...
