repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Certifique-se de incluir a tag/versão
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
