http:
  middlewares:
    auth:
      forwardAuth:
        address: http://auth-service:8000/auth/validate
        trustForwardHeader: true
        authResponseHeaders:
          - X-User-Id
          - X-User-Role
