from typing import Protocol

class IUserRepository(Protocol):
    def save(self, user: User) -> None: ...
    
    def find_by_email(self, email: str) -> User | None: ...
    
    def find_by_id(self, id: int) -> User | None: ...
    
    def find_by_username(self, username: str) -> User | None: ...
    
    def find_all(self) -> list[User]: ...
    
    def update(self, user: User) -> None: ...
    
    def delete(self, id: int) -> None: ...
    
