from typing import Protocol
from src.modules.Agenda.Domain.Entities.AgendaEntity import (
    AgendaCreate,
    AgendaEntity,
    AgendaUpdate,
)


class AgendaRepository(Protocol):
    def create(self, agenda: AgendaCreate) -> AgendaEntity: ...
    def list_all(self) -> list[AgendaEntity]: ...
    def get_by_id(self, agenda_id: int) -> AgendaEntity | None: ...
    def update(self, agenda_id: int, agenda: AgendaUpdate) -> AgendaEntity | None: ...
    def delete(self, agenda_id: int) -> bool: ...