from typing import Protocol


class IAgendaRepository(Protocol):
    def create(self, agenda: AgendaCreate) -> AgendaEntity: ...
    def list_all(self) -> list[AgendaEntity]: ...
    def get_by_id(self, agenda_id: int) -> AgendaEntity | None: ...
    def update(self, agenda_id: int, agenda: AgendaUpdate) -> AgendaEntity | None: ...
    def delete(self, agenda_id: int) -> bool: ...