from typing import Protocol

from ....domain.entities.UserEntity import User


class IAtendenteRepository(Protocol):
    def save(self, user: User) -> User: ...
    def find_by_email(self, email: str) -> User | None: ...
    def find_by_id(self, id: int) -> User | None: ...
    def find_by_username(self, username: str) -> User | None: ...
    def find_all(self) -> list[User]: ...
    def update(self, id: int, data: dict) -> User | None: ...
    def delete(self, id: int) -> bool: ...
