from typing import Protocol

from ....domain.entities.UserEntity import User


class UserRepositoryPort(Protocol):
     async def save(self, user: User) -> User: ...
     async def find_by_email(self, email: str) -> User | None: ...
     async def find_by_id(self, id: str) -> User | None: ...
     async def find_by_username(self, username: str) -> User | None: ...
     async def find_all(self) -> list[User]: ...
     async def update(self, id: str, data: dict) -> User | None: ...
     async def delete(self, id: str) -> bool: ...
     async def add_profile_image(self, id: str, profile_image_url: str, profile_image_object: str) -> None:...


IUserRepository = UserRepositoryPort
